remote_theme: allejo/jekyll-docs-theme@v1.0.0

name: win-vind

project:
  version: 4.2.0
  download_url: https://github.com/pit-ray/win-vind/releases/latest
  download_text: Download

license:
  software: MIT License
  software_url: https://github.com/pit-ray/win-vind/blob/master/LICENSE.txt

links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/pit-ray/win-vind

  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/pit-ray/win-vind

  footer:
    - title: Issues
      icon: bug
      url: https://github.com/pit-ray/win-vind/issues
    - title: Pull requests
      icon: github
      brand: true
      url: https://github.com/pit-ray/win-vind/pulls
    - title: Community
      icon: github
      brand: true
      url: https://github.com/pit-ray/win-vind/discussions

dl_ins_32: https://github.com/pit-ray/win-vind/releases/download/v4.2.0/setup_win-vind_v4.2.0_32bit.exe.zip
dl_zip_32: https://github.com/pit-ray/win-vind/releases/download/v4.2.0/win-vind_v4.2.0_32bit.zip
dl_ins_64: https://github.com/pit-ray/win-vind/releases/download/v4.2.0/setup_win-vind_v4.2.0_64bit.exe.zip
dl_zip_64: https://github.com/pit-ray/win-vind/releases/download/v4.2.0/win-vind_v4.2.0_64bit.zip

ui:
  mode: 'light' # 'auto', 'dark', 'light'
  brand:
    dark: '#00ceff'
    light: '#006eff'
  border_color:
    dark: '#5f5f5f'
    light: '#c8c8c8'
  header:
    trianglify: true
    dark:
      color1: '#062a48'
      color2: '#304e67'
    light:
      color1: '#06121c'
      color2: '#103314'
  masthead:
    color:
      dark: '#fff'
      light: '#e3e3e3'
    align:
      homepage: 'center'
      page: 'left'

social:
  github:
    user: pit-ray
    repo: win-vind

analytics:
  google: UA-121829043-2

# Build settings
markdown: kramdown
