remote_theme: allejo/jekyll-docs-theme@v1.0.0

name: win-vind
logo: favicon.png

url: https://pit-ray.github.io/win-vind

translations:
  - id:
    label: English

  #- id: ja
  #  label: 日本語

project:
  version: 5.13.0
  download_url: downloads
  download_text: Download

license:
  software: MIT License
  software_url: https://github.com/pit-ray/win-vind/blob/master/LICENSE.txt

links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/pit-ray/win-vind

  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/pit-ray/win-vind

  footer:
    - title: Issues
      icon: bug
      url: https://github.com/pit-ray/win-vind/issues

    - title: Community
      icon: comments
      url: https://github.com/pit-ray/win-vind/discussions

dl_ins_32: https://github.com/pit-ray/win-vind/releases/download/v5.13.0/win-vind_5.13.0_32bit_installer.zip
dl_zip_32: https://github.com/pit-ray/win-vind/releases/download/v5.13.0/win-vind_5.13.0_32bit_portable.zip
dl_ins_64: https://github.com/pit-ray/win-vind/releases/download/v5.13.0/win-vind_5.13.0_64bit_installer.zip
dl_zip_64: https://github.com/pit-ray/win-vind/releases/download/v5.13.0/win-vind_5.13.0_64bit_portable.zip

ui:
  mode: 'light' # 'auto', 'dark', 'light'
  brand:
    dark: '#00ceff'
    light: '#006eff'
  border_color:
    dark: '#5f5f5f'
    light: '#c8c8c8'
  header:
    trianglify: false
    dark:
      color1: '#062a48'
      color2: '#304e67'
    light:
      #color1: '#f6f8fa'
      #color2: '#f6f8fa'
      color1: '#fff'
      color2: '#fff'

  masthead:
    color:
      dark: '#fff'
      light: '#4f4f4f'
    align:
      homepage: 'center'
      page: 'left'

analytics:
  google: UA-121829043-2

# Build settings
markdown: kramdown
